"""add collections and view tracking

Revision ID: 04e7e3c760e5
Revises: f5g6h7i8j9k0
Create Date: 2026-03-03 09:52:29.398278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e7e3c760e5'
down_revision: Union[str, Sequence[str], None] = 'f5g6h7i8j9k0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_videos',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'video_id')
    )
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_constraint(op.f('tag_aliases_alias_key'), 'tag_aliases', type_='unique')
    op.drop_index(op.f('ix_tag_aliases_alias'), table_name='tag_aliases')
    op.create_index(op.f('ix_tag_aliases_alias'), 'tag_aliases', ['alias'], unique=True)
    op.add_column('videos', sa.Column('last_viewed_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'view_count')
    op.drop_column('videos', 'last_viewed_at')
    op.drop_index(op.f('ix_tag_aliases_alias'), table_name='tag_aliases')
    op.create_index(op.f('ix_tag_aliases_alias'), 'tag_aliases', ['alias'], unique=False)
    op.create_unique_constraint(op.f('tag_aliases_alias_key'), 'tag_aliases', ['alias'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_table('collection_videos')
    op.drop_table('collections')
    # ### end Alembic commands ###
