"""add auth tables and user_id columns

Revision ID: 07938027ea0d
Revises: g6h7i8j9k0l1
Create Date: 2026-03-06 11:18:36.117259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "07938027ea0d"
down_revision: Union[str, Sequence[str], None] = "g6h7i8j9k0l1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.execute("DELETE FROM collection_videos")
    op.execute("DELETE FROM collections")
    op.execute("DELETE FROM tag_aliases")
    op.execute("DELETE FROM video_jobs")
    op.execute("DELETE FROM videos")
    op.execute("DELETE FROM categories")
    op.add_column("categories", sa.Column("user_id", sa.UUID(), nullable=False))
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=False)
    op.create_unique_constraint(
        "uq_category_user_slug", "categories", ["user_id", "slug"]
    )
    op.create_foreign_key(
        None, "categories", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("collections", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "collections", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("tag_aliases", sa.Column("user_id", sa.UUID(), nullable=False))
    op.drop_index(op.f("ix_tag_aliases_alias"), table_name="tag_aliases")
    op.create_index(
        op.f("ix_tag_aliases_alias"), "tag_aliases", ["alias"], unique=False
    )
    op.create_unique_constraint(
        "uq_tagalias_user_alias", "tag_aliases", ["user_id", "alias"]
    )
    op.create_foreign_key(
        None, "tag_aliases", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("video_jobs", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        None, "video_jobs", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("videos", sa.Column("user_id", sa.UUID(), nullable=False))
    op.drop_constraint(op.f("videos_youtube_id_key"), "videos", type_="unique")
    op.create_unique_constraint(
        "uq_video_user_youtube_id", "videos", ["user_id", "youtube_id"]
    )
    op.create_foreign_key(
        None, "videos", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.drop_constraint("uq_video_user_youtube_id", "videos", type_="unique")
    op.create_unique_constraint(
        op.f("videos_youtube_id_key"),
        "videos",
        ["youtube_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("videos", "user_id")
    op.drop_constraint(None, "video_jobs", type_="foreignkey")
    op.drop_column("video_jobs", "user_id")
    op.drop_constraint(None, "tag_aliases", type_="foreignkey")
    op.drop_constraint("uq_tagalias_user_alias", "tag_aliases", type_="unique")
    op.drop_index(op.f("ix_tag_aliases_alias"), table_name="tag_aliases")
    op.create_index(op.f("ix_tag_aliases_alias"), "tag_aliases", ["alias"], unique=True)
    op.drop_column("tag_aliases", "user_id")
    op.drop_constraint(None, "collections", type_="foreignkey")
    op.drop_column("collections", "user_id")
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_constraint("uq_category_user_slug", "categories", type_="unique")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.drop_column("categories", "user_id")
    op.drop_table("user_settings")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
